repositories {
    mavenCentral()
    google() // Needed for androidx

    // PedroPath v3
    maven { url = "https://repo.dairy.foundation/releases" }
    // Panels dashboard
    maven { url = "https://mymaven.bylazar.com/releases" }
}

dependencies {
    implementation 'org.firstinspires.ftc:Inspection:12.0.0'
    implementation 'org.firstinspires.ftc:Blocks:12.0.0'
    //noinspection Aligned16KB
    implementation 'org.firstinspires.ftc:RobotCore:12.0.0'
    implementation 'org.firstinspires.ftc:RobotServer:12.0.0'
    implementation 'org.firstinspires.ftc:OnBotJava:12.0.0'
    implementation 'org.firstinspires.ftc:Hardware:12.0.0'
    implementation 'org.firstinspires.ftc:FtcCommon:12.0.0'
    implementation 'org.firstinspires.ftc:Vision:12.0.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'

    // 16750/20403 external dependencies:
    implementation 'com.pedropathing:revhub:3.0.1'
    implementation 'com.pedropathing:tuning:1.0.0'
    implementation 'com.bylazar:fullpanels:1.0.12'
}
